// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wA73ZswqroE6r1m1xaxGJ1
// Component: SbmFAmFl460
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: wA73ZswqroE6r1m1xaxGJ1/projectcss
import sty from "./PlasmicHeaderMadisonopoly.module.css"; // plasmic-import: SbmFAmFl460/css

export type PlasmicHeaderMadisonopoly__VariantMembers = {};

export type PlasmicHeaderMadisonopoly__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeaderMadisonopoly__VariantsArgs;
export const PlasmicHeaderMadisonopoly__VariantProps =
  new Array<VariantPropType>();

export type PlasmicHeaderMadisonopoly__ArgsType = {};
type ArgPropType = keyof PlasmicHeaderMadisonopoly__ArgsType;
export const PlasmicHeaderMadisonopoly__ArgProps = new Array<ArgPropType>();

export type PlasmicHeaderMadisonopoly__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultHeaderMadisonopolyProps {
  className?: string;
}

function PlasmicHeaderMadisonopoly__RenderFunc(props: {
  variants: PlasmicHeaderMadisonopoly__VariantsArgs;
  args: PlasmicHeaderMadisonopoly__ArgsType;
  overrides: PlasmicHeaderMadisonopoly__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeaderMadisonopoly__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeaderMadisonopoly__VariantsArgs;
    args?: PlasmicHeaderMadisonopoly__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeaderMadisonopoly__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHeaderMadisonopoly__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeaderMadisonopoly__ArgProps,
          internalVariantPropNames: PlasmicHeaderMadisonopoly__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHeaderMadisonopoly__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeaderMadisonopoly";
  } else {
    func.displayName = `PlasmicHeaderMadisonopoly.${nodeName}`;
  }
  return func;
}

export const PlasmicHeaderMadisonopoly = Object.assign(
  // Top-level PlasmicHeaderMadisonopoly renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHeaderMadisonopoly
    internalVariantProps: PlasmicHeaderMadisonopoly__VariantProps,
    internalArgProps: PlasmicHeaderMadisonopoly__ArgProps
  }
);

export default PlasmicHeaderMadisonopoly;
/* prettier-ignore-end */
